# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/katlas',
                'doc_host': 'https://sky1ove.github.io',
                'git_url': 'https://github.com/sky1ove/katlas',
                'lib_path': 'katlas'},
  'syms': { 'katlas.core': { 'katlas.core.Data': ('core.html#data', 'katlas/core.py'),
                             'katlas.core.Data.__init__': ('core.html#data.__init__', 'katlas/core.py'),
                             'katlas.core.Data.get_kinase_info': ('core.html#data.get_kinase_info', 'katlas/core.py'),
                             'katlas.core.Data.get_kinase_norm': ('core.html#data.get_kinase_norm', 'katlas/core.py'),
                             'katlas.core.Data.get_kinase_raw': ('core.html#data.get_kinase_raw', 'katlas/core.py'),
                             'katlas.core.Data.get_standard_unstack': ('core.html#data.get_standard_unstack', 'katlas/core.py'),
                             'katlas.core.norm': ('core.html#norm', 'katlas/core.py'),
                             'katlas.core.plot_logo': ('core.html#plot_logo', 'katlas/core.py'),
                             'katlas.core.raw2kinase': ('core.html#raw2kinase', 'katlas/core.py'),
                             'katlas.core.raw2logo': ('core.html#raw2logo', 'katlas/core.py')}}}
