# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/katlas',
                'doc_host': 'https://sky1ove.github.io',
                'git_url': 'https://github.com/sky1ove/katlas',
                'lib_path': 'katlas'},
  'syms': {'katlas.core': {'katlas.core.foo': ('core.html#foo', 'katlas/core.py')}}}
