"""Load various kinase-relatd datasets"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_data.ipynb.

# %% auto #0
__all__ = ['Data', 'CPTAC']

# %% ../nbs/00_data.ipynb #34ccf9ea
import os
import pandas as pd
from filelock import FileLock
from functools import lru_cache
from fastcore.all import patch_to

import gdown,zipfile,shutil,tempfile
from pathlib import Path


# %% ../nbs/00_data.ipynb #5fb47d59
def _normalize_dataset_dir(path: str | Path) -> Path:
    resolved_path = Path(path).expanduser().resolve()
    return resolved_path if resolved_path.name == "katlas_dataset" else resolved_path / "katlas_dataset"


# %% ../nbs/00_data.ipynb #a451e307
def _default_dataset_dir() -> Path:
    env_path = os.getenv("KATLAS_DATA_DIR")
    if env_path:
        return _normalize_dataset_dir(env_path)
    return Path(tempfile.gettempdir()) / "katlas_dataset"


# %% ../nbs/00_data.ipynb #a3b2f927
class Data:
    "A class for fetching various datasets."
    DATASET_DIR = _default_dataset_dir()


# %% ../nbs/00_data.ipynb #48509c58
def _normalize_required_files(
    required_files: str | Path | list[str | Path] | None,  # Required dataset members
) -> tuple[str, ...]:
    if required_files is None:
        return tuple()

    items = [required_files] if isinstance(required_files, (str, Path)) else required_files
    return tuple(str(Path(item)) for item in items)


# %% ../nbs/00_data.ipynb #1d968dbb
@lru_cache
def _read_dataset_file_cached(path: str) -> pd.DataFrame:
    file_path = Path(path)
    ext = file_path.suffix.lower()

    if ext == ".csv":
        df = pd.read_csv(file_path)
    elif ext == ".parquet":
        df = pd.read_parquet(file_path)
    else:
        raise ValueError(f"Unsupported file type: {ext}. Supported types: .csv, .parquet")

    return df.rename(columns={"Unnamed: 0": "kinase"}) if "Unnamed: 0" in df.columns else df


# %% ../nbs/00_data.ipynb #7d19c094
@patch_to(Data)
def clear_cache() -> None:
    _read_dataset_file_cached.cache_clear()


# %% ../nbs/00_data.ipynb #305149b4
@patch_to(Data)
def download(
    download_dir: str | Path | None = None,  # Parent directory or katlas_dataset folder
    force: bool = False,  # Re-download even if the folder already exists
    verbose: bool = True,  # Print status messages
    required_files: str | Path | list[str | Path] | None = None,  # Files that must exist after download
) -> None:
    """Download dataset zip and extract to folder."""

    url = "https://drive.google.com/uc?id=17wIl0DbdoHV036Z3xgaT_0H3LlM_W47l"

    if download_dir is not None:
        Data.DATASET_DIR = _normalize_dataset_dir(download_dir)

    dataset_dir = Data.DATASET_DIR
    zip_path = dataset_dir.parent / "katlas_dataset.zip"
    lock_path = dataset_dir.parent / "katlas_dataset.lock"
    required_list = _normalize_required_files(required_files)

    dataset_dir.parent.mkdir(parents=True, exist_ok=True)
    with FileLock(str(lock_path)):
        missing_files = [rel_path for rel_path in required_list if not (dataset_dir / rel_path).exists()]
        needs_download = force or not dataset_dir.exists() or bool(missing_files)

        if not needs_download:
            if verbose:
                print(f"✅ Dataset exists at: {dataset_dir}")
            return

        Data.clear_cache()

        if dataset_dir.exists():
            if verbose:
                if force:
                    print(f"♻️ Removing existing folder: {dataset_dir}")
                else:
                    print(f"♻️ Dataset is missing {missing_files}; re-downloading to {dataset_dir}")
            shutil.rmtree(dataset_dir)

        dataset_dir.mkdir(parents=True, exist_ok=True)

        if verbose:
            print("⬇️ Downloading katlas_dataset.zip ...")

        downloaded_file = gdown.download(url, output=str(zip_path), quiet=not verbose)

        if downloaded_file is None or not Path(downloaded_file).exists():
            raise RuntimeError(
                "Dataset download failed. "
                "Please check your internet connection or Google Drive permissions."
            )

        if verbose:
            print(f"📂 Extracting to {dataset_dir} ...")

        with zipfile.ZipFile(downloaded_file, "r") as zip_ref:
            for member in zip_ref.namelist():
                member_path = dataset_dir / member
                if not member_path.resolve().is_relative_to(dataset_dir.resolve()):
                    raise RuntimeError(f"Unsafe zip file detected (zip-slip): {member}")
            zip_ref.extractall(dataset_dir)

        missing_after = [rel_path for rel_path in required_list if not (dataset_dir / rel_path).exists()]
        if missing_after:
            raise FileNotFoundError(
                f"Dataset download completed, but these files are still missing: {missing_after}"
            )

        try:
            if verbose:
                print(f"🧹 Removing zip file: {downloaded_file}")
            Path(downloaded_file).unlink()
        except Exception as e:
            if verbose:
                print(f"⚠️ Could not remove {downloaded_file}: {e}")

        if verbose:
            print(f"✅ Done! Extracted dataset is at: {dataset_dir}")


# %% ../nbs/00_data.ipynb #a508476b
@patch_to(Data)
def read_file(
    rel_path: str | Path,  # Relative path inside katlas_dataset
    auto_download: bool = True,  # Download the dataset bundle if the file is missing
) -> pd.DataFrame:
    """Load a CSV or Parquet file from the local dataset folder."""

    rel_path_str = str(Path(rel_path))
    if auto_download:
        Data.download(verbose=False, required_files=rel_path_str)

    path = Data.DATASET_DIR / rel_path_str
    if not path.exists():
        raise FileNotFoundError(
            f"Dataset file not found: {path}. "
            f"Call Data.download(required_files={rel_path_str!r}) or pass auto_download=True."
        )

    return _read_dataset_file_cached(str(path.resolve())).copy()


# %% ../nbs/00_data.ipynb #d8037ca8
_DATASET_PATHS = {
    "get_kinase_info": "kinase_info.csv",
    "get_kinase_uniprot": "uniprot_human_keyword_kinase.parquet",
    "get_kd_uniprot": "uniprot_kd_labeled.parquet",
    "get_pspa_tyr": "PSPA/pspa_tyr_norm.parquet",
    "get_pspa_st": "PSPA/pspa_st_norm.parquet",
    "get_pspa": "PSPA/pspa_all_norm.parquet",
    "get_pspa_raw": "PSPA/pspa_all_raw.parquet",
    "get_pspa_scale": "PSPA/pspa_all_scale.parquet",
    "get_pspa_st_pct": "PSPA/pspa_pct_st.parquet",
    "get_pspa_tyr_pct": "PSPA/pspa_pct_tyr.parquet",
    "get_num_dict": "PSPA/pspa_divide_num.csv",
    "get_ks_unique": "CDDM/unique_ks_sites.parquet",
    "get_ks_dataset": "CDDM/ks_datasets_20250407.parquet",
    "get_ks_background": "CDDM/ks_background.parquet",
    "get_cddm": "CDDM/pssms.parquet",
    "get_cddm_upper": "CDDM/pssms_upper.parquet",
    "get_cddm_LO": "CDDM/pssms_LO.parquet",
    "get_cddm_LO_upper": "CDDM/pssms_LO_upper.parquet",
    "get_aa_info": "amino_acids/aa_info.parquet",
    "get_aa_rdkit": "amino_acids/aa_rdkit.parquet",
    "get_aa_morgan": "amino_acids/aa_morgan.parquet",
    "get_cptac_ensembl_site": "phosphosites/linkedOmicsKB_ref_pan.parquet",
    "get_cptac_unique_site": "phosphosites/cptac_unique_site.parquet",
    "get_cptac_gene_site": "phosphosites/linkedOmics_ref_pan.parquet",
    "get_psp_human_site": "phosphosites/psp_human.parquet",
    "get_ochoa_site": "phosphosites/ochoa_site.parquet",
    "get_combine_site_psp_ochoa": "phosphosites/combine_site_psp_ochoa.parquet",
    "get_combine_site_phosphorylated": "phosphosites/phosphorylated_combine_site.parquet",
    "get_human_site": "phosphosites/phosphorylated_combine_site20.parquet",
    "get_reactome_pathway_lo": "reactome_lowest_level.parquet",
    "get_reactome_pathway": "reactome_all_levels.parquet",
}

# %% ../nbs/00_data.ipynb #7a739408
def _read_named_dataset(
    dataset_name: str,  # Registry key from _DATASET_PATHS
) -> pd.DataFrame:
    "Load a bundled katlas dataset by registry name."
    try:
        rel_path = _DATASET_PATHS[dataset_name]
    except KeyError as exc:
        raise KeyError(f"Unknown dataset name: {dataset_name}") from exc
    return Data.read_file(rel_path)

# %% ../nbs/00_data.ipynb #36b703e4
@patch_to(Data)
def get_kinase_info() -> pd.DataFrame:
    """
    Get information of 523 human kinases on kinome tree.
    Group, family, and subfamily classifications are sourced from Coral;
    full protein sequences are retrieved using UniProt IDs;
    kinase domain sequences are obtained from KinaseDomain.com;
    and cellular localization data is extracted from published literature.
    """
    return _read_named_dataset("get_kinase_info")

# %% ../nbs/00_data.ipynb #03b7efd0
@patch_to(Data)
def get_kinase_uniprot() -> pd.DataFrame:
    """
    Get information of 672 uniprot human kinases, which were retrieved from UniProt by filtering all human protein entries using the keyword 'kinase'.
    It includes additional pseudokinases and lipid kinases.
    """
    return _read_named_dataset("get_kinase_uniprot")

# %% ../nbs/00_data.ipynb #d20cc783
@patch_to(Data)
def get_kd_uniprot() -> pd.DataFrame:
    "Kinase domains extracted from UniProt database. "
    return _read_named_dataset("get_kd_uniprot")

# %% ../nbs/00_data.ipynb #aef6622b
@patch_to(Data)
def get_pspa_tyr() -> pd.DataFrame:
    """Get PSPA normalized data of tyrosine kinase."""
    return _read_named_dataset("get_pspa_tyr")

# %% ../nbs/00_data.ipynb #cec0e3f4
@patch_to(Data)
def get_pspa_st() -> pd.DataFrame:
    """Get PSPA normalized data of serine/threonine kinase."""
    return _read_named_dataset("get_pspa_st")

# %% ../nbs/00_data.ipynb #fa155596
@patch_to(Data)
def get_pspa() -> pd.DataFrame:
    """Get PSPA normalized data of serine/threonine and tyrosine kinases.
    pS is duplicate of pT;
    For all kinases:
        -pS is duplicate of pT
    S/T kinases:
        - Column normalized to 17 (20 standard-S,T,C) or 16 (20-S,T,C,Y;PDHK1 & PDHK4) amino acids.
        - C is median of 17 or 16 (PDHK1 & PDHK4) amino acids
    TK (including _TYR which is non-canonical):
        - Column normalized to 18 (20-Y,C; canonical +TNNI3K,WEE1) or 16 (20-S,T,Y,C; IRR, JAK3, MST1R + non-canonical _TYR) aa.
        - Y is duplicate of F;
        - C is median of 18 or 16 amino acids.
"""
    return _read_named_dataset("get_pspa")

# %% ../nbs/00_data.ipynb #c9c0011e
@patch_to(Data)
def get_pspa_raw(
    include_s: bool = False,  # Keep pS columns, which duplicate pT
) -> pd.DataFrame:
    """Get PSPA raw data of serine/threonine and tyrosine kinases."""
    df = _read_named_dataset("get_pspa_raw")
    if not include_s:
        df = df.loc[:, ~df.columns.str.endswith("s")]
    return df.copy()

# %% ../nbs/00_data.ipynb #390f8e41
@patch_to(Data)
def get_pspa_scale() -> pd.DataFrame:
    """
    Get PSPA (-5 to +4) scaled data from PSPA normalized data.
    Each position (including both pS/pT and pS=pT) are normalized to 1.
    """
    return _read_named_dataset("get_pspa_scale")

# %% ../nbs/00_data.ipynb #2bf9fd7f
@patch_to(Data)
def get_pspa_st_pct() -> pd.DataFrame:
    """Get PSPA reference score to calculate percentile for serine/threonine kinases."""
    return _read_named_dataset("get_pspa_st_pct")

# %% ../nbs/00_data.ipynb #fe09c492
@patch_to(Data)
def get_pspa_tyr_pct() -> pd.DataFrame:
    """Get PSPA reference score to calculate percentile for tyrosine kinases."""
    return _read_named_dataset("get_pspa_tyr_pct")

# %% ../nbs/00_data.ipynb #f12962c3
@patch_to(Data)
def get_num_dict() -> dict[str, int]:
    """Get a dictionary mapping kinase to number of random amino acids in PSPA."""
    return _read_named_dataset("get_num_dict").set_index("kinase")["num_random_aa"].to_dict()

# %% ../nbs/00_data.ipynb #95e100e5
@patch_to(Data)
def get_ks_unique() -> pd.DataFrame:
    """Get kinase substrate dataset with unique sub site ID."""
    return _read_named_dataset("get_ks_unique")

# %% ../nbs/00_data.ipynb #3966fade
@patch_to(Data)
def get_ks_dataset(
    add_kinase_info: bool = True,  # Merge kinase annotation columns into the substrate table
) -> pd.DataFrame:
    """Get kinase-substrate pairs collected from public resources."""
    df = _read_named_dataset("get_ks_dataset")

    df.columns = [
        int(c) if isinstance(c, str) and c.lstrip("-").isdigit() else c
        for c in df.columns
    ]

    if "substrate_phosphoseq" in df.columns:
        df["substrate_sequence"] = df["substrate_phosphoseq"].str.upper()

    if not add_kinase_info:
        return df

    info = (
        Data.get_kinase_info()
        .sort_values("kinase")
        .drop_duplicates("uniprot")
        .set_index("uniprot")
    )

    df["uniprot_clean"] = df["kinase_uniprot"].str.split("-", n=1).str[0]

    maps = {
        "kinase_group": info["modi_group"].to_dict(),
        "kinase_family": info["family"].to_dict(),
        "kinase_subfamily": info["subfamily"].to_dict(),
        "kinase_pspa_big": info["pspa_category_big"].to_dict(),
        "kinase_pspa_small": info["pspa_category_small"].to_dict(),
        "kinase_coral_ID": info["ID_coral"].to_dict(),
        "kinase_protein": info["kinase"].to_dict(),
    }

    gene_map = Data.get_kinase_uniprot().set_index("Entry")["Gene Names"].to_dict()

    df["kinase_on_tree"] = df["uniprot_clean"].isin(info.index).astype(int)
    df["kinase_genes"] = df["uniprot_clean"].map(gene_map)

    for col, mapping in maps.items():
        df[col] = df["uniprot_clean"].map(mapping)

    site_info = Data.get_ks_unique()[["sub_site", "num_kin"]].set_index("sub_site")
    df["num_kin"] = df["sub_site"].map(site_info["num_kin"])
    df.drop(columns="uniprot_clean", inplace=True)
    return df

# %% ../nbs/00_data.ipynb #32d187d0
@patch_to(Data)
def get_ks_background() -> pd.DataFrame:
    """Get kinase substrate dataset with unique sub site ID."""
    return _read_named_dataset("get_ks_background")

# %% ../nbs/00_data.ipynb #ab60578b
@patch_to(Data)
def get_cddm() -> pd.DataFrame:
    """Get the CDDM dataset."""
    return _read_named_dataset("get_cddm")

# %% ../nbs/00_data.ipynb #43b8a96e
@patch_to(Data)
def get_cddm_upper() -> pd.DataFrame:
    """Get the CDDM dataset of all uppercase sequence."""
    return _read_named_dataset("get_cddm_upper")

# %% ../nbs/00_data.ipynb #12495078
@patch_to(Data)
def get_cddm_LO() -> pd.DataFrame:
    """Get CDDM Log-odds data with 'STY' background."""
    return _read_named_dataset("get_cddm_LO")

# %% ../nbs/00_data.ipynb #1156d798
@patch_to(Data)
def get_cddm_LO_upper() -> pd.DataFrame:
    """Get CDDM Log-odds data of all-uppercase sequence with 'STY' background."""
    return _read_named_dataset("get_cddm_LO_upper")

# %% ../nbs/00_data.ipynb #53011b71
@patch_to(Data)
def get_aa_info() -> pd.DataFrame:
    """Get amino acid information."""
    return _read_named_dataset("get_aa_info")

# %% ../nbs/00_data.ipynb #9af474dd
@patch_to(Data)
def get_aa_rdkit() -> pd.DataFrame:
    """Get RDKit representations of amino acids."""
    return _read_named_dataset("get_aa_rdkit")

# %% ../nbs/00_data.ipynb #0193809d
@patch_to(Data)
def get_aa_morgan() -> pd.DataFrame:
    """Get Morgan fingerprint representations of amino acids."""
    return _read_named_dataset("get_aa_morgan")

# %% ../nbs/00_data.ipynb #d3af40c7
@patch_to(Data)
def get_cptac_ensembl_site() -> pd.DataFrame:
    """Get CPTAC dataset with unique EnsemblProteinID+site."""
    return _read_named_dataset("get_cptac_ensembl_site")

# %% ../nbs/00_data.ipynb #ef3f1ccf
@patch_to(Data)
def get_cptac_unique_site() -> pd.DataFrame:
    """Get CPTAC dataset with unique site sequences."""
    return _read_named_dataset("get_cptac_unique_site")

# %% ../nbs/00_data.ipynb #9dfb987b
@patch_to(Data)
def get_cptac_gene_site() -> pd.DataFrame:
    """Get CPTAC dataset with unique Gene+site."""
    return _read_named_dataset("get_cptac_gene_site")

# %% ../nbs/00_data.ipynb #6bf2435b
@patch_to(Data)
def get_psp_human_site() -> pd.DataFrame:
    """Get PhosphoSitePlus human dataset (Gene+site)."""
    return _read_named_dataset("get_psp_human_site")

# %% ../nbs/00_data.ipynb #39e15af0
@patch_to(Data)
def get_ochoa_site() -> pd.DataFrame:
    """Get phosphoproteomics dataset from Ochoa et al."""
    return _read_named_dataset("get_ochoa_site")

# %% ../nbs/00_data.ipynb #9cabd935
@patch_to(Data)
def get_combine_site_psp_ochoa() -> pd.DataFrame:
    """
    Get the combined dataset from Ochoa and PhosphoSitePlus.
    """
    return _read_named_dataset("get_combine_site_psp_ochoa")

# %% ../nbs/00_data.ipynb #c3b636a4
@patch_to(Data)
def get_combine_site_phosphorylated() -> pd.DataFrame:
    """
    Get the combined phosphorylated dataset from Ochoa and PhosphoSitePlus.
    """
    return _read_named_dataset("get_combine_site_phosphorylated")

# %% ../nbs/00_data.ipynb #ba1afbae
@patch_to(Data)
def get_human_site() -> pd.DataFrame:
    """
    Get the combined phosphorylated dataset from Ochoa and PhosphoSitePlus (20-length version).
    """
    return _read_named_dataset("get_human_site")

# %% ../nbs/00_data.ipynb #c5f1296e
@patch_to(Data)
def get_reactome_pathway_lo() -> pd.DataFrame:
    """
    Get lowest reactome pathways with Uniprot ID as identifier.
    """
    return _read_named_dataset("get_reactome_pathway_lo")

# %% ../nbs/00_data.ipynb #e08802eb
@patch_to(Data)
def get_reactome_pathway() -> pd.DataFrame:
    """
    Get all level reactome pathways with Uniprot ID as identifier.
    """
    path_all = _read_named_dataset("get_reactome_pathway")
    # path_lo = Data.get_reactome_pathway_lo()
    # path_all['lowest'] = path_all.reactome_id.isin(path_lo.reactome_id).astype(int)
    return path_all

# %% ../nbs/00_data.ipynb #5e04dfc3
class CPTAC:

    "A class for fetching CPTAC phosphoproteomics data."

    @staticmethod
    def _read_file(
        cancer: str,  # CPTAC cancer type
        is_Tumor: bool = True,  # Tumor tissue or normal tissue
        is_KB: bool = False,  # LinkedOmicsKB protein-site identifiers instead of gene-site
    ) -> pd.DataFrame:
        "Fetch the CPTAC phosphoproteomics table for one cancer type."

        sample_type = "Tumor" if is_Tumor else "Normal"
        id_url = f"https://zenodo.org/records/8196130/files/bcm-{cancer.lower()}-mapping-gencode.v34.basic.annotation-mapping.txt.gz"
        data_url = f"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/{cancer.upper()}/{cancer.upper()}_phospho_site_abundance_log2_reference_intensity_normalized_{sample_type}.txt"

        ref = pd.read_csv(id_url, compression="gzip", sep="\t")[["protein", "gene", "gene_name"]]
        ref = ref.drop_duplicates().reset_index(drop=True)

        try:
            raw = pd.read_csv(data_url, sep="\t")
        except Exception as e:
            raise RuntimeError(f"Failed to load CPTAC data for {cancer}: {e}") from e

        info = pd.DataFrame(
            {
                "gene": raw.idx.str.split("|").str[0],
                "site": raw.idx.str.split("|").str[2],
                "site_seq": raw.idx.str.split("|").str[3],
            }
        )

        print(f"the {cancer} dataset length is: {info.shape[0]}")

        info = info.merge(ref, "left")
        print(f"after id mapping, the length is {info.shape[0]}")
        print(f"{info.gene_name.isna().sum()} sites does not have a mapped gene name")

        info["gene_site"] = info["gene_name"] + "_" + info["site"]
        info["protein_site"] = info["protein"].str.split(".").str[0] + "_" + info["site"]

        info = info.drop_duplicates(subset="protein_site" if is_KB else "gene_site").reset_index(drop=True)
        print(f"after removing duplicates of protein_site, the length is {info.shape[0]}")
        return info


# %% ../nbs/00_data.ipynb #53e305a9
@patch_to(CPTAC)
def list_cancer() -> list[str]:
    "List available CPTAC cancer type"
    return ['HNSCC','GBM','COAD','CCRCC','LSCC','BRCA','UCEC','LUAD','PDAC','OV']

# %% ../nbs/00_data.ipynb #ce91102e
@patch_to(CPTAC)
def get_id(
    cancer_type: str,  # CPTAC cancer type
    is_Tumor: bool = True,  # Tumor tissue or normal tissue
    is_KB: bool = False,  # LinkedOmicsKB protein-site identifiers instead of gene-site
) -> pd.DataFrame:
    "Get CPTAC phosphorylation site information for one cancer type."
    if cancer_type not in CPTAC.list_cancer():
        raise ValueError("cancer type is not included, check available cancer types from CPTAC.list_cancer()")
    return CPTAC._read_file(cancer_type, is_Tumor, is_KB)

