"""Plot hierarchical clustering for PSSMs"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_hierarchical.ipynb.

# %% auto #0
__all__ = ['get_1d_js', 'get_1d_js_parallel']

# %% ../nbs/07_hierarchical.ipynb #bd699391
from .compare import js_divergence_flat
from kplot.hierarchical import get_1d_distance, get_1d_distance_parallel

# %% ../nbs/07_hierarchical.ipynb #05173dfd
def get_1d_js(df): 
    "Compute 1D distance using JS divergence."
    return get_1d_distance(df,js_divergence_flat)

# %% ../nbs/07_hierarchical.ipynb #712cddb1
def get_1d_js_parallel(df, func_flat=js_divergence_flat, **kwargs): 
    "Compute 1D distance matrix using JS divergence."
    return get_1d_distance_parallel(df, func_flat=func_flat, **kwargs)
