"""calculation of log-odds PSSM and visualization"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_lo.ipynb.

# %% auto #0
__all__ = ['get_pssm_LO', 'get_pssm_LO_flat', 'plot_logo_LO', 'plot_logo_heatmap_LO']

# %% ../nbs/04_lo.ipynb #6c844d16-6bcb-4452-a41e-b0ce25ea86ab
import numpy as np
from matplotlib import pyplot as plt

from .data import Data
from .plot import _plot_logo_heatmap_layout, convert_logo_df, plot_heatmap, plot_logo_raw
from .pssm import EPSILON, recover_pssm, get_prob, flatten_pssm

# %% ../nbs/04_lo.ipynb #77d2dcc5-1020-42fb-8774-879ad764c226
def get_pssm_LO(pssm_df,
                site_type, # S, T, Y, ST, or STY
               ):
    "Get log odds PSSM: log2 (freq pssm/background pssm)."
    bg_pssms = Data.get_ks_background()
    flat_bg = bg_pssms.loc[f'ks_{site_type}']
    pssm_bg = recover_pssm(flat_bg)
    pssm_odds = ((pssm_df+EPSILON)/(pssm_bg+EPSILON)).dropna(axis=0,how='all').dropna(axis=1, how='all')
    # make sure all columns and index matched
    if pssm_odds.shape != pssm_df.shape: raise ValueError("Shape mismatch between PSSM and background PSSM.")
    return np.log2(pssm_odds).replace([np.inf, -np.inf], 0).fillna(0)

# %% ../nbs/04_lo.ipynb #4171e816-92b1-4c59-86af-e72946ecfd51
def get_pssm_LO_flat(flat_pssm,
                    site_type, # S, T, Y, ST, or STY
                    ):
    pssm_df = recover_pssm(flat_pssm)
    return get_pssm_LO(pssm_df,site_type)

# %% ../nbs/04_lo.ipynb #ae9329ff-1f25-45f5-93b2-15d7389a8c3b
def plot_logo_LO(pssm_LO,title="Motif", acceptor=None, scale_zero=True,scale_pos_neg=True,ax=None,figsize=(10,1)):
    "Plot logo of log-odds given a frequency PSSM."
    if acceptor is not None:
        acceptor_upper = acceptor.upper()
        if acceptor_upper not in ["S", "T", "Y"]:
            raise ValueError(f"Acceptor must be one of 'S', 'T', or 'Y'; got {acceptor_upper!r}")
        pssm_LO = pssm_LO.copy()
        target_row = acceptor_upper.lower() if acceptor_upper.lower() in pssm_LO.index else acceptor_upper
        if target_row not in pssm_LO.index:
            pssm_LO.loc[target_row] = 0.0
        pssm_LO.loc[target_row, 0] = 0.1

    pssm_LO = convert_logo_df(pssm_LO,scale_zero=scale_zero,scale_pos_neg=scale_pos_neg)
    ytitle = "Scaled Log-Odds" if scale_pos_neg else "Log-Odds (bits)"
    plot_logo_raw(pssm_LO,ax=ax,title=title,ytitle=ytitle,figsize=figsize)

# %% ../nbs/04_lo.ipynb #b0e2452e-414a-4698-b5bf-6a7995af5649
def plot_logo_heatmap_LO(pssm_LO, # pssm of log-odds
                             title='Motif',
                         acceptor=None,
                             figsize=(17,10),
                             include_zero=False,
                         scale_pos_neg=True
                      ):
    """Plot logo and heatmap of enrichment bits vertically"""
    _plot_logo_heatmap_layout(
        heatmap_df=pssm_LO,
        logo_plotter=lambda ax: plot_logo_LO(
            pssm_LO,
            acceptor=acceptor,
            ax=ax,
            title=title,
            scale_pos_neg=scale_pos_neg,
        ),
        figsize=figsize,
        include_zero=include_zero,
        heatmap_kwargs={"scale_pos_neg": scale_pos_neg, "colorbar_title": "bits"},
    )
