"""Object interface for position-specific probability, background, log-odds, and motif plots."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_pm.ipynb.

# %% auto #0
__all__ = ['PositionMatrix']

# %% ../nbs/10_pm.ipynb #04704afd
from collections.abc import Sequence
from dataclasses import dataclass, field
from typing import Literal

import pandas as pd
from matplotlib import pyplot as plt
from matplotlib.axes import Axes

from .data import Data
from .lo import get_pssm_LO, plot_logo_LO, plot_logo_heatmap_LO
from .plot import plot_heatmap, plot_logo, plot_logo_heatmap
from katlas.pssm import (
    flatten_pssm,
    get_IC,
    get_entropy,
    get_prob,
    get_specificity,
    pssm_to_seq,
    recover_pssm,
)

# %% ../nbs/10_pm.ipynb #fe4d5581
@dataclass
class PositionMatrix:
    "Position-specific matrix wrapper for probability, background, log-odds, and motif plots."

    data: pd.DataFrame | pd.Series | Sequence[str] | None = None
    seq_col: str = "site_seq"
    bg_type: str = "STY"
    name: str = "Motif"
    pssm_df: pd.DataFrame | None = None
    bg_pssm: pd.DataFrame | None = None
    bg_seq: pd.DataFrame | pd.Series | Sequence[str] | None = None

    default_kind: Literal["prob", "log_odds"] = field(default="prob", init=False)
    title: str = field(default="", init=False)

    _prob: pd.DataFrame | None = field(default=None, init=False, repr=False)
    _bg_prob: dict[str, pd.DataFrame] = field(default_factory=dict, init=False, repr=False)
    _log_odds: dict[str | int, pd.DataFrame] = field(default_factory=dict, init=False, repr=False)

    def __post_init__(self) -> None:
        self.bg_type = self.bg_type.upper()

        if self.bg_pssm is not None and self.bg_seq is not None:
            raise ValueError("Pass either bg_pssm or bg_seq, not both.")

        if self.bg_pssm is not None:
            self.bg_pssm = self._clean_matrix(self.bg_pssm)

        elif self.bg_seq is not None:
            self.bg_pssm = self._clean_matrix(
                get_prob(
                    self.bg_seq,
                    seq_col=self.seq_col,
                )
            )

        self.default_kind = "log_odds" if self.bg_pssm is not None else "prob"

        if self.pssm_df is not None:
            self._prob = self._clean_matrix(self.pssm_df)
            self.title = self._make_title()
            return

        if isinstance(self.data, pd.DataFrame) and self.seq_col not in self.data.columns:
            if self._is_matrix_like(self.data):
                self._prob = self._clean_matrix(self.data)
                self.data = None
                self.title = self._make_title()
                return

        if self.data is None:
            raise ValueError("Pass sequence data or a precomputed probability matrix.")

        self.title = self._make_title()

    @classmethod
    def from_flat(
        cls,
        flat_pssm: pd.Series,  # Flattened PSSM indexed as position+residue keys
        bg_type: str = "STY",  # S, T, Y, ST, or STY background model
        name: str = "Motif",  # Display name used by plotting helpers
        bg_pssm: pd.DataFrame | None = None,  # Optional background PSSM
        bg_seq: pd.DataFrame | pd.Series | Sequence[str] | None = None,  # Optional background sequences
        bg_seq_col: str | None = None,  # Sequence column for bg_seq if it is a dataframe
    ) -> "PositionMatrix":
        "Create a PositionMatrix from a flattened PSSM Series."
        return cls(
            pssm_df=recover_pssm(flat_pssm),
            bg_type=bg_type,
            name=name,
            bg_pssm=bg_pssm,
            bg_seq=bg_seq,
            bg_seq_col=bg_seq_col,
        )

    @staticmethod
    def _is_matrix_like(data: pd.DataFrame) -> bool:
        "Return True when a dataframe looks like an amino-acid x position matrix."
        if data.empty:
            return False

        try:
            [int(col) for col in data.columns]
        except (TypeError, ValueError):
            return False

        return all(isinstance(idx, str) for idx in data.index)

    @staticmethod
    def _clean_matrix(matrix: pd.DataFrame) -> pd.DataFrame:
        "Copy a matrix and normalize position labels to integer columns when possible."
        clean = matrix.copy()

        try:
            clean.columns = [int(col) for col in clean.columns]
        except (TypeError, ValueError):
            pass

        return clean.sort_index(axis=1)

    @staticmethod
    def _normalize_kind(kind: str) -> str:
        "Normalize matrix aliases used by convenience methods."
        normalized = kind.lower().replace("-", "_")
        aliases = {
            "lo": "log_odds",
            "logodds": "log_odds",
            "bg": "background",
        }
        return aliases.get(normalized, normalized)

    def _resolve_bg_type(
        self,
        bg_type: str | None = None,  # Optional background model override
    ) -> str:
        "Return an uppercase background model name."
        return self.bg_type if bg_type is None else bg_type.upper()

    def _make_title(self) -> str:
        "Return the default plot title with sample size when available."
        if self.data is None:
            return self.name

        try:
            return f"{self.name} (n={len(self.data):,})"
        except TypeError:
            return self.name

    def prob(self) -> pd.DataFrame:
        "Return the probability PSSM, computing it lazily from sequence data if needed."
        if self._prob is None:
            self._prob = self._clean_matrix(
                get_prob(self.data, seq_col=self.seq_col)
            )

        return self._prob.copy()

    def bg_prob(
        self,
        bg_type: str | None = None,  # Optional S/T/Y/ST/STY background override
        align: bool = True,  # Align returned rows and columns to this matrix
    ) -> pd.DataFrame:
        "Return the background probability PSSM."

        if bg_type is None and self.bg_pssm is not None:
            bg_prob = self.bg_pssm.copy()

        else:
            resolved_bg_type = self._resolve_bg_type(bg_type)

            if resolved_bg_type not in self._bg_prob:
                bg_pssms = Data.ks_background()
                self._bg_prob[resolved_bg_type] = self._clean_matrix(
                    recover_pssm(bg_pssms.loc[f"ks_{resolved_bg_type}"])
                )

            bg_prob = self._bg_prob[resolved_bg_type].copy()

        if align:
            prob = self.prob()
            return bg_prob.reindex(index=prob.index, columns=prob.columns)

        return bg_prob

    def log_odds(
        self,
        bg_type: str | None = None,  # Optional S/T/Y/ST/STY background override
        bg_pssm: pd.DataFrame | None = None,  # Alternative background PSSM
    ) -> pd.DataFrame:
        "Return log2(probability/background) for this matrix."

        if bg_pssm is not None:
            active_bg_pssm = self._clean_matrix(bg_pssm)
            cache_key: str | int = id(bg_pssm)

        elif bg_type is None and self.bg_pssm is not None:
            active_bg_pssm = self.bg_pssm
            cache_key = "init_bg_pssm"

        else:
            active_bg_pssm = None
            cache_key = self._resolve_bg_type(bg_type)

        if cache_key not in self._log_odds:
            self._log_odds[cache_key] = self._clean_matrix(
                get_pssm_LO(
                    self.prob(),
                    bg_type=bg_type,
                    bg_pssm=active_bg_pssm,
                )
            )

        return self._log_odds[cache_key].copy()

    def matrix(
        self,
        kind: Literal["prob", "log_odds", "lo", "background", "bg"] | None = None,
        bg_type: str | None = None,  # Optional background model override
    ) -> pd.DataFrame:
        "Return one of the probability, background, or log-odds matrices."

        if kind is None:
            kind = self.default_kind

        normalized = self._normalize_kind(kind)

        if normalized == "prob":
            return self.prob()

        if normalized == "background":
            return self.bg_prob(bg_type=bg_type)

        if normalized == "log_odds":
            return self.log_odds(bg_type=bg_type)

        raise ValueError("kind must be one of: prob, background, bg, log_odds, lo")

    def flat(
        self,
        kind: Literal["prob", "log_odds", "lo", "background", "bg"] | None = None,
        bg_type: str | None = None,  # Optional background model override
        column_wise: bool = True,  # Flatten by columns when True, rows when False
    ) -> pd.Series:
        "Return a flattened matrix Series with position+residue keys."
        matrix = self.matrix(kind=kind, bg_type=bg_type)
        return pd.Series(flatten_pssm(matrix, column_wise=column_wise))

    def seq(
        self,
        thr: float = 0.2,  # Probability threshold for showing residues
        clean_center: bool = True,  # Keep only s/t/y values at the center
    ) -> str:
        "Return a compact consensus sequence string from the probability PSSM."
        return pssm_to_seq(self.prob(), thr=thr, clean_center=clean_center)

    def entropy(self, **kwargs: object) -> pd.Series | float:
        "Return entropy per position or the minimum entropy when return_min=True."
        return get_entropy(self.prob(), **kwargs)

    def ic(self, **kwargs: object) -> pd.Series:
        "Return information content per position for the probability PSSM."
        return get_IC(self.prob(), **kwargs)

    def specificity(self) -> float:
        "Return the existing katlas specificity score for the probability PSSM."
        return get_specificity(self.prob())

    def logo(
        self,
        kind: Literal["prob", "log_odds", "lo"] | None = None,  # Logo matrix to plot
        title: str | None = None,  # Optional plot title
        acceptor: str | None = None,  # S/T/Y center residue hint for log-odds logos
        scale_zero: bool = True,  # Rescale center stack for visual balance
        scale_pos_neg: bool = True,  # Rescale signed log-odds logo heights
        ax: Axes | None = None,  # Matplotlib axis to draw on
        figsize: tuple[float, float] = (10, 1),  # Figure size when ax is None
    ) -> Axes:
        "Draw a probability or log-odds logo and return the axis."

        if kind is None:
            kind = self.default_kind

        if ax is None:
            _, ax = plt.subplots(figsize=figsize)

        plot_title = self.title if title is None else title
        normalized = self._normalize_kind(kind)

        if normalized == "prob":
            plot_logo(
                self.prob(),
                title=plot_title,
                scale_zero=scale_zero,
                ax=ax,
                figsize=figsize,
            )

        elif normalized == "log_odds":
            plot_logo_LO(
                self.log_odds(),
                title=plot_title,
                acceptor=acceptor,
                scale_zero=scale_zero,
                scale_pos_neg=scale_pos_neg,
                ax=ax,
                figsize=figsize,
            )

        else:
            raise ValueError("kind must be 'prob', 'log_odds', or 'lo'.")

        return ax

    def heatmap(
        self,
        kind: Literal["prob", "log_odds", "lo", "background", "bg"] | None = None,
        bg_type: str | None = None,  # Optional background model override
        ax: Axes | None = None,  # Matplotlib axis to draw on
        position_label: bool = True,  # Show position labels along the x axis
        figsize: tuple[float, float] = (5, 6),  # Figure size when ax is None
        include_zero: bool = False,  # Include the center position in the heatmap
        scale_pos_neg: bool | None = None,  # Use signed scaling; defaults by matrix type
        colorbar_title: str | None = None,  # Optional colorbar title
        **kwargs: object,  # Extra keyword arguments passed to plot_heatmap
    ) -> Axes:
        "Draw a heatmap for probability, background, or log-odds values."

        if kind is None:
            kind = self.default_kind

        normalized = self._normalize_kind(kind)
        matrix = self.matrix(kind=normalized, bg_type=bg_type)

        if scale_pos_neg is None:
            scale_pos_neg = normalized == "log_odds"

        if colorbar_title is None:
            colorbar_title = "bits" if normalized == "log_odds" else "Prob."

        return plot_heatmap(
            matrix,
            ax=ax,
            position_label=position_label,
            figsize=figsize,
            include_zero=include_zero,
            scale_pos_neg=scale_pos_neg,
            colorbar_title=colorbar_title,
            **kwargs,
        )

    def logo_heatmap(
        self,
        kind: Literal["prob", "log_odds", "lo"] | None = None,
        title: str | None = None,  # Optional plot title
        acceptor: str | None = None,  # S/T/Y center residue hint for log-odds logos
        figsize: tuple[float, float] = (17, 10),  # Figure size
        include_zero: bool = False,  # Include the center position in the heatmap
        scale_pos_neg: bool = True,  # Rescale signed log-odds logo heights
    ) -> None:
        "Draw the standard katlas logo plus heatmap layout."

        if kind is None:
            kind = self.default_kind

        plot_title = self.title if title is None else title
        normalized = self._normalize_kind(kind)

        if normalized == "prob":
            plot_logo_heatmap(
                self.prob(),
                title=plot_title,
                figsize=figsize,
                include_zero=include_zero,
            )

        elif normalized == "log_odds":
            plot_logo_heatmap_LO(
                self.log_odds(),
                title=plot_title,
                acceptor=acceptor,
                figsize=figsize,
                include_zero=include_zero,
                scale_pos_neg=scale_pos_neg,
            )

        else:
            raise ValueError("kind must be 'prob', 'log_odds', or 'lo'.")

    def clear_cache(self) -> None:
        "Clear cached probability, background, and log-odds matrices."

        if self.data is not None:
            self._prob = None

        self._bg_prob.clear()
        self._log_odds.clear()
