project:
  type: website

format:
  html:
    theme:
      - minty
      - custom.scss
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/sky1ove/kdock
  sidebar:
    style: floating
    contents:
      - text: "Get Started"
        href: index.ipynb
      - section: Tutorials
        contents: tutorials/*
      - section: Modules
        contents: 
            - "*.ipynb"
            - "!*/*.ipynb"
      - section: 2025 NC Paper
        contents: paper/*

metadata-files: [nbdev.yml]