project:
  type: website

format:
  html:
    theme:
      - minty
      - custom.scss
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/sky1ove/katlas
  sidebar:
    style: floating
    contents:
      - text: "Get Started"
        href: index.ipynb
      - section: Tutorials
        contents: tutorials/*
      - section: Modules
        contents:
            - 00_data.ipynb
            - 01_preprocess.ipynb
            - 02_pssm.ipynb
            - 03_score.ipynb
            - 04_feature.ipynb
            - 05_plot.ipynb
            - 06_ML.ipynb
            - 07_DL.ipynb
            - 08_analyze.ipynb
      - section: 2025 NC Paper
        contents: paper/*

metadata-files: [nbdev.yml]